In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np
from sklearn.linear_model import LinearRegression

df1 = pd.read_csv('citibike-tripdata.csv') # df1: contains citibike data
df2 = pd.read_csv('usedcars.csv') # df2: contains used car data

df2 = df2.replace("?", np.nan) 
df2=df2.dropna(subset=["price"], axis=0) # drop row that missing value in "price"
df2["price"] = df2["price"].astype("int")
df2=df2.dropna(subset=["horsepower"], axis=0)
df2=df2.dropna(subset=["peak-rpm"], axis=0)
df2["horsepower"]=df2["horsepower"].astype("int")
df2["peak-rpm"]=df2["peak-rpm"].astype("int")

## save this usedcar data (after formatting) as usedcars_update.csv
df2.to_csv("usedcars_update.csv")



In [2]:
lm=LinearRegression()

X=df2[["highway-mpg"]] # Define the predictor variable
Y=df2["price"] # Define the target variable

model=lm.fit(X,Y) # using fit() method to fit the model, i.e., to find the pratameters b_0 and b_1
### model = LinearRegression().fit(X,Y)
#print(lm.fit(X,Y))

In [17]:
### The attributes of model are .intercept_ which represent b_0
### and .coef_ which represent b_1

In [76]:
print(model.coef_)

[-821.50472215]


In [77]:
print(model.intercept_)

38450.00418821089


In [20]:
### Hence, yhat=b_0+b_1x 
### price = 38450.004 - 821.5* (highway-mpg)

In [78]:
## We want to predict the price when (highway-mpg) is 25
y_pred = model.intercept_ + model.coef_ * 25
y_pred

array([17912.38613444])

In [79]:
## Or 
C=np.array([25]).reshape((-1,1)) # reshapre((# of row, # of columm)) 
# .reshape((-1,1)): number of column is 1, the number of row is inferred from the length of 
#- the array and the remaning dimension
C # after applied reshape((-1,1)), C is now a column vector
y_pred2=model.predict(C)
y_pred2

array([17912.38613444])

In [70]:
D=np.array([24,25,26]).reshape((-1,1))
D

array([[24],
       [25],
       [26]])

In [44]:
### R^2
r_sq=model.score(X,Y)

In [45]:
r_sq

0.4973491560296689

In [4]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [85]:
lm=LinearRegression()
model=lm.fit(x,y)

In [86]:
model.intercept_

5.633333333333329

In [87]:
model.coef_

array([0.54])

In [90]:
y_pre = model.predict(x)
y_pre

array([ 8.33333333, 13.73333333, 19.13333333, 24.53333333, 29.93333333,
       35.33333333])

In [103]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((6,1 ))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [7]:
x = np.array([5, 15, 25, 35, 45, 55])#.reshape((-1,1 ))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)
print(y)

[ 5 15 25 35 45 55]
[ 5 20 14 32 22 38]
